### PR TITLE
Add support for multi-arch Docker builds (amd64, arm64)

### LINKED ISSUE #101: Docker arm64 support
Hi, first of all thank you for maintaining this project, it is very useful and works really well.

I have a problem though on my raspberry pi where I want to use the docker image of the project compiled on `GOARCH=arm64`.
Currently, this doesn't seem possible. I followed [these steps](https://github.com/viaduct-ai/kustomize-sops#ksops-repo-sever-patch) to install the plugin in `argocd-repo-server` but without chance, since the image is not currently compiled in the arm64 architecture.

I feel like we might need to make changes to the `.goreleaser.yml` file and maybe add a `Dockerfile.arm64` or something like that to be able to build cross architecture images.

### PR DESCRIPTION
**Pull request by cguertin14**
Closes #101 

This PR adds support for arm64 docker images by modifying the `Dockerfile` and `.goreleaser.yml` files.
As can be seen in [GoReleaser's docs](https://goreleaser.com/customization/docker/), we can enable the use of `docker buildx` with a boolean value, which is what is done in this PR.

Also, I followed [this guide](https://carlosbecker.com/posts/multi-platform-docker-images-goreleaser-gh-actions/) to apply modifications which I tested in my fork.

### CODE REVIEW

**Comment by cguertin14** [comment]
Tested on my PC with the following commands:

1- `linux/amd64`
```bash
$ docker run --platform linux/amd64 --rm -it cguertz/ksops:v2.5.1-multi-arch-3
root@c14379f618b8:/go/src/github.com/viaduct-ai/kustomize-sops#
```

1- `linux/arm64` (on an arm64-capable machine)
```bash
$ docker run --platform linux/arm64 --rm -it cguertz/ksops:v2.5.1-multi-arch-3
root@c14379f618b8:/go/src/github.com/viaduct-ai/kustomize-sops#
```

**Comment by swiftdiaries** [comment]
LGTM

**Review by swiftdiaries — APPROVED** [review]

**Review by devstein — APPROVED** [review]
@cguertin14 Thank you for contributing! Looks great

**Comment by cguertin14** [comment]
> @cguertin14 Thank you for contributing! Looks great

thanks to you!

**Pull request merged**
