### PR TITLE
Update aws sdk version

### PR DESCRIPTION
**Pull request by unixninja92**
I updated `github.com/aws/aws-sdk-go-v2` to `v1.28.0` to support new ways of auth including IRSA and Pod Identity in EKS. This updated the other aws sdk versions as well. I ran tests and everything passed.

### CODE REVIEW

**Review by devstein — APPROVED** [review]
Thank you for contributing @unixninja92! I'll try cut a release soon

**Comment by truongnht** [comment]
@devstein are you sure this merge will work? I thought the aws sdk come from sops?

**Comment by devstein** [comment]
good call and good timing -> https://github.com/viaduct-ai/kustomize-sops/pull/258

**Comment by truongnht** [comment]
@devstein if you look into #258, you would see the aws sdk version turns out differently (higher version than this PR). The indirect comment means it is indirectly deduced from `sops`. So I hope this kind of PR would be rejected next time to avoid confusion.

**Pull request merged**
